application: sdh-games
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: /static/index.html
- url: /rpc/.*
  script: _go_app
- url: /_ah/channel/.*
  script: _go_app

inbound_services:
- channel_presence
